#!/usr/bin/env sh
set -e

container_mode=${CONTAINER_MODE:-"http"}

if [ ${container_mode} = "http" ]; then
    exec php artisan octane:status 
elif [ ${container_mode} = "horizon" ]; then
    exec php artisan horizon:status
elif [ ${container_mode} = "worker" ]; then
    process_id="$(cat /var/run/worker.pid)"
    echo "Process id: $process_id"
    if [ -f "/proc/$process_id/status" ]; then
        echo "Worker proccess: running"
        exit 0
    else 
        echo "Worker proccess: stopped"
        exit 1
    fi
else
    echo "Container mode mismatched."
    exit 1
fi